### ISSUE TITLE
Saucelab manual Testing not working for IOS device

### ISSUE THREAD

**Issue by Jogi0210** [saucelabs/appium-inspector-saucelabs#27]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

Saucelab manual Testing not working for IOS device

## Environment

- I am running Appium Desktop version _2022.2.1-saucelabs.1.
- I am on
    - [x] Windows

**Comment by wswebcreation** [comment]
Hi @Jogi0210 

Can you please provide some more information about what is not working? Do you have screenshots, your capabilities, logs and so on.

**Comment by wswebcreation** [comment]
Hi @Jogi0210 

What can't you do?

**Comment by Jogi0210** [comment]
When clicking on "Saucelabs Manual Testing Button", I am not able to perform manual steps on the app. It just showing as normal screen

**Comment by wswebcreation** [comment]
Hmm, I've been trying to debug this but I haven't seen this. Can you contact me on wim.selles@saucelabs.com so we can discuss it there?
